-- Board-game quick guides. Run once in the Supabase SQL editor.

create table if not exists public.game_guides (
  id bigint generated by default as identity primary key,
  slug text not null,
  version_key text not null,
  title_ko text not null,
  title_en text not null,
  aliases text[] not null default '{}',
  edition_label text not null,
  release_year smallint,
  player_count text not null,
  play_time text not null,
  goal text not null,
  setup text[] not null default '{}',
  gameplay text[] not null default '{}',
  special_rules text[] not null default '{}',
  pirate_abilities text[] not null default '{}',
  scoring text[] not null default '{}',
  end_condition text not null,
  source_name text not null,
  source_url text not null,
  sort_order smallint not null default 0,
  published boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint game_guides_slug_version_unique unique (slug, version_key)
);

-- Keeps this migration re-runnable for databases created with the earlier guide schema.
alter table public.game_guides add column if not exists special_rules text[] not null default '{}';
alter table public.game_guides add column if not exists pirate_abilities text[] not null default '{}';

alter table public.game_guides enable row level security;
drop policy if exists "game_guides_public_read" on public.game_guides;
create policy "game_guides_public_read" on public.game_guides for select to anon, authenticated using (published = true);
grant select on public.game_guides to anon, authenticated;

insert into public.game_guides
  (slug, version_key, title_ko, title_en, aliases, edition_label, release_year, player_count, play_time, goal, setup, gameplay, special_rules, scoring, end_condition, source_name, source_url, sort_order)
values
  ('saboteur', 'base-2004', '사보타지', 'Saboteur', array['사포타지', '세이버투어'], '기본판', 2004, '3~10명', '약 30분',
   '금광꾼은 출발지에서 금이 있는 목적지까지 길을 연결하고, 방해꾼은 정체를 숨긴 채 이를 저지합니다.',
   array['인원수에 맞게 금광꾼과 방해꾼 역할 카드를 섞어 각자 비밀리에 1장씩 받습니다.', '출발 카드와 뒷면으로 섞은 목적지 카드 3장을 정해진 간격으로 놓고 길·행동 카드를 나눠 받습니다.'],
   array['차례마다 길 카드 놓기, 행동 카드 사용, 카드 1장 버리기 중 하나를 한 뒤 덱에서 1장을 뽑습니다.', '길은 출발지와 끊김 없이 연결되어야 하며, 도구가 고장 난 동안에는 길 카드를 놓을 수 없습니다.', '금이 있는 목적지까지 길이 닿거나 더 이상 카드를 낼 수 없으면 라운드가 끝납니다.'],
   array['도구 파손: 지정한 사람의 광산 수레·랜턴·곡괭이 중 하나를 고장 냅니다.', '도구 수리: 카드에 표시된 도구 하나를 수리합니다. 두 도구가 그려진 카드는 둘 중 하나만 수리합니다.', '지도: 목적지 카드 1장을 혼자 확인한 뒤 원래대로 덮습니다.', '낙석: 출발지와 목적지를 제외한 길 카드 1장을 제거합니다.'],
   array['금에 도달하면 금광꾼들이 금 카드를 나눠 갖고, 실패하면 방해꾼들이 인원수에 따른 금을 받습니다.'],
   '총 3라운드 후 모은 금 조각이 가장 많은 사람이 승리합니다.', 'AMIGO Saboteur 공식 규칙', 'https://blog.amigo-spiele.de/content/ap/rule/04900-GB-AmigoRule.pdf', 10),

  ('love-letter', 'classic-2012', '러브레터', 'Love Letter', array['러브 레터'], '클래식 구성 · 2012', 2012, '2~4명', '약 20분',
   '상대를 탈락시키거나 라운드 종료 시 가장 높은 인물 카드를 보유해 호감 토큰을 모읍니다.',
   array['16장의 인물 카드를 섞어 1장을 보지 않고 제외하고 각자 1장씩 받습니다.', '2인 게임에서는 추가로 3장을 앞면으로 제외합니다.'],
   array['차례가 되면 카드 1장을 뽑아 손의 2장 중 1장을 내고 그 능력을 적용합니다.', '카드 효과로 탈락하면 다음 라운드까지 행동하지 않습니다.', '한 명만 남거나 덱이 떨어지면 라운드가 끝나며, 덱이 떨어진 경우 손의 숫자가 가장 높은 사람이 승리합니다.'],
   array['근위병(1): 근위병을 제외한 인물을 지목해 상대 손패를 맞히면 상대가 탈락합니다.', '사제(2): 다른 한 사람의 손패를 몰래 확인합니다.', '남작(3): 다른 한 사람과 손패 숫자를 비교해 낮은 쪽이 탈락합니다.', '시녀(4): 다음 자기 차례까지 다른 카드 효과의 대상이 되지 않습니다.', '왕자(5): 자신을 포함한 한 사람에게 손패를 버리고 새로 뽑게 합니다. 공주를 버리면 탈락합니다.', '왕(6): 다른 한 사람과 손패를 교환합니다.', '백작부인(7): 왕이나 왕자와 함께 들고 있다면 반드시 백작부인을 내야 합니다.', '공주(8): 어떤 이유로든 내거나 버리면 즉시 탈락합니다.'],
   array['라운드 승자는 호감 토큰 1개를 받습니다.', '승리에 필요한 토큰은 2인 7개, 3인 5개, 4인 4개입니다.'],
   '필요한 호감 토큰을 먼저 모은 사람이 승리합니다.', 'Z-Man Games Love Letter 공식 규칙', 'https://www.zmangames.com/game/love-letter/', 20),

  ('love-letter', 'expanded-2019', '러브레터', 'Love Letter', array['러브 레터'], '확장 구성 · 2019 이후', 2019, '2~6명', '약 20분',
   '상대를 탈락시키거나 라운드 종료 시 가장 높은 인물 카드를 보유해 호감 토큰을 모읍니다.',
   array['스파이와 수상 등을 포함한 21장의 인물 카드를 섞어 1장을 보지 않고 제외하고 각자 1장씩 받습니다.', '2인 게임에서는 추가로 3장을 앞면으로 제외합니다.'],
   array['차례가 되면 카드 1장을 뽑아 손의 2장 중 1장을 내고 그 능력을 적용합니다.', '한 명만 남거나 덱이 떨어지면 라운드가 끝납니다.', '스파이는 그 라운드에 스파이를 공개한 생존자가 혼자라면 추가 호감 토큰을 주고, 수상은 카드를 2장 더 본 뒤 원하는 1장만 남기게 합니다.'],
   array['스파이(0): 직접 효과는 없지만 라운드 생존자 중 스파이를 공개한 사람이 혼자라면 호감 토큰 1개를 추가로 받습니다.', '근위병(1): 근위병을 제외한 인물을 지목해 상대 손패를 맞히면 상대가 탈락합니다.', '사제(2): 다른 한 사람의 손패를 몰래 확인합니다.', '남작(3): 다른 한 사람과 손패 숫자를 비교해 낮은 쪽이 탈락합니다.', '시녀(4): 다음 자기 차례까지 다른 카드 효과의 대상이 되지 않습니다.', '왕자(5): 자신을 포함한 한 사람에게 손패를 버리고 새로 뽑게 합니다. 공주를 버리면 탈락합니다.', '수상(6): 덱에서 2장을 더 보고 총 3장 중 1장을 남긴 뒤 나머지를 덱 맨 아래에 둡니다.', '왕(7): 다른 한 사람과 손패를 교환합니다.', '백작부인(8): 왕이나 왕자와 함께 들고 있다면 반드시 백작부인을 내야 합니다.', '공주(9): 어떤 이유로든 내거나 버리면 즉시 탈락합니다.'],
   array['라운드 승자는 호감 토큰 1개를 받습니다.', '승리에 필요한 토큰은 2인 6개, 3인 5개, 4인 4개, 5~6인 3개입니다.'],
   '필요한 호감 토큰을 먼저 모은 사람이 승리합니다.', 'Z-Man Games Love Letter 공식 규칙', 'https://www.zmangames.com/game/love-letter/', 20),

  ('wizard', 'base', '위자드', 'Wizard', array['위저드'], '기본판', 1984, '3~6명', '약 45분',
   '매 라운드 자신이 가져갈 트릭 수를 정확히 예측해 가장 많은 점수를 얻습니다.',
   array['첫 라운드는 1장, 다음 라운드는 2장처럼 라운드마다 손패가 1장씩 늘어납니다.', '남은 덱의 맨 위 카드를 공개해 트럼프 색을 정합니다. 위자드면 딜러가 색을 고르고 광대면 트럼프가 없습니다.'],
   array['각자 예상 트릭 수를 공개한 뒤 선부터 카드 1장씩 냅니다.', '일반 카드는 선도 무늬를 따라야 하지만 위자드와 광대는 언제든 낼 수 있습니다.', '첫 위자드, 가장 높은 트럼프, 선도 무늬의 가장 높은 숫자 순으로 트릭을 가져갑니다.'],
   array['위자드: 언제든 낼 수 있으며 해당 트릭에서 가장 먼저 나온 위자드가 승리합니다.', '광대: 언제든 낼 수 있고 보통 가장 약합니다. 광대로 트릭을 시작하면 다음 일반 카드가 선도 무늬를 정하며, 모두 광대라면 첫 광대가 승리합니다.', '마지막 라운드는 모든 카드를 나누므로 트럼프 카드가 없습니다.'],
   array['예측 성공: 기본 20점 + 획득 트릭당 10점.', '예측 실패: 예측과 실제 트릭 차이당 -10점.'],
   '카드를 모두 나누는 마지막 라운드까지 진행한 뒤 총점이 가장 높은 사람이 승리합니다.', 'AMIGO Wizard 공식 규칙', 'https://blog.amigo-spiele.de/content/ap/rule/06900-GB-AmigoRule.pdf', 30),

  ('skull-king', 'ko-current', '스컬킹', 'Skull King', array['스컬 킹'], '한국어판 · 현재 점수 계산기 기준', 2022, '2~8명', '약 30분',
   '매 라운드 자신이 가져갈 트릭 수를 예측하고 정확히 맞혀 가장 높은 점수를 얻습니다.',
   array['총 10라운드를 진행하며 1라운드 1장부터 매 라운드 손패를 1장씩 늘립니다.', '카드를 확인한 뒤 모두 동시에 이번 라운드의 예상 트릭 수를 선언합니다.'],
   array['선도 무늬가 있으면 같은 무늬를 내야 하며, 없으면 다른 숫자 카드나 특수 카드를 냅니다.', '기본 우선순위는 일반 색상보다 검정 해적기가 강합니다. 인어는 스컬킹을, 스컬킹은 해적을, 해적은 인어를 이깁니다.', '크라켄은 해당 트릭을 무효로 하고 흰고래는 특수 카드를 탈출로 취급합니다. 약탈품 동맹은 양쪽 모두 비드를 맞혀야 보너스를 받습니다.'],
   array['탈출: 가장 약한 카드입니다. 탈출로 시작하면 다음 숫자 카드가 선도 색을 정하며 모두 탈출이면 첫 탈출이 승리합니다.', '해적: 모든 숫자 카드와 인어를 이기지만 스컬킹에게 집니다.', '인어: 숫자 카드를 이기고 해적에게 지지만 스컬킹을 이깁니다. 스컬킹과 인어가 함께 있으면 인어가 트릭을 가져갑니다.', '스컬킹: 모든 해적과 숫자 카드를 이기지만 인어에게 집니다.', '크라켄: 해당 트릭에는 승자가 없고 아무도 카드를 가져가지 않습니다.', '흰고래: 특수 카드를 탈출처럼 취급하고 가장 높은 숫자 카드가 승리합니다.', '약탈품: 낸 사람과 트릭 승자가 동맹이 되며 둘 다 비드를 맞히면 각각 +20점을 받습니다.'],
   array['1개 이상 비드 성공: 획득 트릭당 +20점, 실패: 차이당 -10점.', '0 비드 성공: 라운드 수 × +10점, 실패: 라운드 수 × -10점.', '비드 성공 시 해적으로 인어 장당 +20점, 스컬킹으로 해적 장당 +30점, 인어로 스컬킹 +40점 등 카드 보너스를 더합니다.'],
   '10라운드 종료 후 총점이 가장 높은 사람이 승리합니다.', 'Grandpa Beck’s Games 공식 규칙 및 현재 앱 한국어판 규칙', 'https://www.grandpabecksgames.com/pages/skull-king', 40),

  ('tichu', 'base', '티츄', 'Tichu', array['TICHU'], '기본판', 1991, '4명 팀전', '약 60분',
   '2명씩 한 팀이 되어 손의 카드를 먼저 없애고 카드 점수와 티츄 선언 점수로 1000점에 먼저 도달합니다.',
   array['마주 앉은 두 사람이 한 팀이 되고 각자 14장씩 가져갑니다.', '각자 다른 세 사람에게 카드 1장씩을 건넨 뒤 받은 카드를 확인합니다.'],
   array['마작을 가진 사람이 시작하며 싱글, 페어, 트리플, 풀하우스, 연속 페어, 스트레이트 중 하나를 냅니다.', '다음 사람은 같은 종류·같은 장수의 더 높은 조합을 내거나 패스합니다. 폭탄은 차례와 관계없이 낼 수 있습니다.', '세 명이 카드를 모두 털면 한 판이 끝납니다. 한 팀이 1·2등을 모두 하면 즉시 원투 피니시가 됩니다.'],
   array['마작(1): 첫 플레이어를 정하고, 낼 때 일반 숫자 하나를 소원으로 지정할 수 있습니다. 낼 수 있는 사람은 반드시 그 숫자를 포함해 내야 합니다.', '개: 새 트릭을 시작할 때만 내며 선도권을 맞은편 팀원에게 넘깁니다.', '봉황: 조합에서 숫자 카드를 대신할 수 있습니다. 단독으로는 직전에 나온 카드보다 0.5 높고 점수는 -25점입니다.', '용: 가장 강한 단일 카드이며 트릭 점수는 +25점입니다. 가져간 트릭은 상대 한 명에게 줘야 합니다.', '폭탄: 같은 숫자 4장 또는 같은 무늬의 5장 이상 연속 카드입니다. 차례와 관계없이 낼 수 있고 더 높은 폭탄으로만 이길 수 있습니다. 스트레이트 플러시 폭탄은 포카드 폭탄보다 강합니다.', '티츄 선언: 스몰은 첫 카드를 내기 전, 라지는 첫 8장을 본 뒤 나머지 카드를 보기 전에 선언합니다. 선언자가 첫 번째로 손을 털어야 성공합니다.'],
   array['5는 5점, 10과 K는 10점, 용은 +25점, 봉황은 -25점입니다.', '세 번째 사람이 손을 털면 마지막 사람의 남은 손패 점수는 상대 팀에, 마지막 사람이 모은 트릭은 첫 번째로 나간 사람에게 줍니다.', '원투 피니시 팀은 카드 점수 대신 200점을 받습니다.', '스몰 티츄 성공/실패는 ±100점, 라지 티츄는 ±200점입니다.'],
   '어느 팀이 1000점 이상에 도달한 판 종료 시 더 높은 총점의 팀이 승리합니다.', 'Rio Grande Games Tichu 공식 규칙', 'https://www.riograndegames.com/wp-content/uploads/2013/02/Tichu-Rules.pdf', 50),

  ('vulture', 'ko', '독수리 눈치싸움', 'Hol''s der Geier', array['홀스 데어 가이어', 'Raj', 'Beat the Buzzard'], '한국어판', 1988, '2~5명', '약 20분',
   '숫자 카드를 눈치 있게 사용해 플러스 점수 카드는 얻고 마이너스 점수 카드는 피합니다.',
   array['각자 같은 색의 숫자 카드 1~15를 모두 받습니다.', '+1~+10과 -1~-5 점수 카드 15장을 섞어 가운데에 둡니다.'],
   array['점수 카드 1장을 공개하고 모두 손에서 숫자 카드 1장을 골라 뒷면으로 냅니다.', '동시에 공개해 플러스 점수는 가장 높은 단독 숫자가, 마이너스 점수는 가장 낮은 단독 숫자가 가져갑니다.', '같은 숫자는 서로 무효가 됩니다. 받을 사람이 없으면 점수 카드를 남겨 다음 점수 카드와 함께 판정합니다.', '사용한 숫자 카드는 다시 사용하지 않습니다.'],
   array['같은 숫자를 낸 사람들은 모두 판정에서 제외됩니다. 그다음으로 높거나 낮은 단독 숫자가 점수 카드를 가져갑니다.', '모든 숫자가 동점으로 무효라면 점수 카드를 다음 라운드로 넘겨 새 점수 카드와 합쳐서 가져갑니다.'],
   array['획득한 플러스와 마이너스 점수 카드를 모두 합산합니다.'],
   '15라운드 후 총점이 가장 높은 사람이 승리합니다.', 'AMIGO Hol’s der Geier 공식 게임 안내', 'https://www.amigo-spiele.de/hols-der-geier_1943_1210', 60)
on conflict (slug, version_key) do update set
  title_ko = excluded.title_ko,
  title_en = excluded.title_en,
  aliases = excluded.aliases,
  edition_label = excluded.edition_label,
  release_year = excluded.release_year,
  player_count = excluded.player_count,
  play_time = excluded.play_time,
  goal = excluded.goal,
  setup = excluded.setup,
  gameplay = excluded.gameplay,
  special_rules = excluded.special_rules,
  scoring = excluded.scoring,
  end_condition = excluded.end_condition,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  sort_order = excluded.sort_order,
  published = true,
  updated_at = now();

update public.game_guides
set pirate_abilities = array[
  '로지 드레이니: 트릭 승자가 다음 트릭의 선도자를 지정합니다.',
  '강도 바히즈: 카드 2장을 뽑은 뒤 손에서 2장을 버립니다.',
  '로아탄의 라스칼: 비드 성공에 10점 또는 20점을 걸며 실패하면 해당 점수를 잃습니다.',
  '후아니타 하데: 나눠주지 않은 카드 더미를 혼자 확인합니다.',
  '거인 해리: 자신의 비드를 +1, -1 또는 그대로 유지합니다.'
], updated_at = now()
where slug = 'skull-king' and version_key = 'ko-current';
