-- Board Game Score - Supabase schema
-- Authentication uses an internal address derived from the login ID. The UI never asks for email.

create extension if not exists citext with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  login_id extensions.citext not null unique,
  display_name text not null,
  created_at timestamptz not null default now(),
  constraint profiles_login_id_format check (login_id::text ~ '^[a-z0-9_]{4,20}$'),
  constraint profiles_display_name_length check (char_length(btrim(display_name)) between 1 and 20)
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  constraint friendships_different_users check (requester_id <> addressee_id)
);

create unique index if not exists friendships_pair_unique
  on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));

create table if not exists public.user_presence (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  last_seen_at timestamptz not null default now()
);

create table if not exists public.game_rooms (
  id uuid primary key default gen_random_uuid(),
  game_id text not null check (game_id in ('skullking', 'tichu', 'generic')),
  game_mode text not null,
  host_user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'completed')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  expires_at timestamptz not null default (now() + interval '2 hours')
);

create table if not exists public.game_participants (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.game_rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  display_name text not null,
  team_name text,
  final_score integer,
  final_rank integer,
  created_at timestamptz not null default now(),
  constraint game_participants_name_length check (char_length(btrim(display_name)) between 1 and 50),
  constraint game_participants_rank_positive check (final_rank is null or final_rank > 0)
);

create unique index if not exists game_participants_room_user_unique
  on public.game_participants(room_id, user_id) where user_id is not null;

create index if not exists user_presence_last_seen_idx on public.user_presence(last_seen_at);
create index if not exists game_rooms_active_expiry_idx on public.game_rooms(expires_at) where status = 'active';
create index if not exists game_participants_user_idx on public.game_participants(user_id) where user_id is not null;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.user_presence enable row level security;
alter table public.game_rooms enable row level security;
alter table public.game_participants enable row level security;

drop policy if exists "profiles_read_self" on public.profiles;
create policy "profiles_read_self" on public.profiles for select to authenticated
  using (id = auth.uid());
drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self" on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "friendships_read_own" on public.friendships;
create policy "friendships_read_own" on public.friendships for select to authenticated
  using (requester_id = auth.uid() or addressee_id = auth.uid());

drop policy if exists "presence_read_self" on public.user_presence;
create policy "presence_read_self" on public.user_presence for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "rooms_read_participating" on public.game_rooms;
drop policy if exists "rooms_read_host" on public.game_rooms;
create policy "rooms_read_host" on public.game_rooms for select to authenticated
  using (host_user_id = auth.uid());

drop policy if exists "participants_read_participating" on public.game_participants;
create policy "participants_read_participating" on public.game_participants for select to authenticated
  using (user_id = auth.uid() or exists (
    select 1 from public.game_rooms gr where gr.id = room_id and gr.host_user_id = auth.uid()
  ));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  requested_id text := lower(btrim(new.raw_user_meta_data ->> 'login_id'));
  requested_name text := btrim(new.raw_user_meta_data ->> 'display_name');
begin
  if requested_id is null or requested_id !~ '^[a-z0-9_]{4,20}$' then
    raise exception 'invalid_login_id';
  end if;
  if requested_name is null or char_length(requested_name) not between 1 and 20 then
    raise exception 'invalid_display_name';
  end if;
  if lower(coalesce(new.email, '')) <> (requested_id || '@danbi-score.pages.dev') then
    raise exception 'invalid_internal_identity';
  end if;

  insert into public.profiles (id, login_id, display_name)
  values (new.id, requested_id, requested_name);
  insert into public.user_presence (user_id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_login_id_available(candidate text)
returns boolean
language sql
security definer set search_path = ''
as $$
  select candidate is not null
    and lower(btrim(candidate)) ~ '^[a-z0-9_]{4,20}$'
    and not exists (
      select 1 from public.profiles p where p.login_id = lower(btrim(candidate))
    );
$$;

create or replace function public.my_profile()
returns table(id uuid, login_id text, display_name text)
language sql
security definer set search_path = ''
as $$
  select p.id, p.login_id::text, p.display_name
  from public.profiles p where p.id = auth.uid();
$$;

create or replace function public.search_profiles(login_id_prefix text)
returns table(user_id uuid, login_id text, display_name text)
language sql
security definer set search_path = ''
as $$
  select p.id, p.login_id::text, p.display_name
  from public.profiles p
  where auth.uid() is not null
    and p.id <> auth.uid()
    and left(lower(p.login_id::text), char_length(lower(btrim(login_id_prefix)))) = lower(btrim(login_id_prefix))
    and char_length(btrim(login_id_prefix)) > 0
    and not exists (
      select 1 from public.friendships f
      where (f.requester_id = auth.uid() and f.addressee_id = p.id)
        or (f.addressee_id = auth.uid() and f.requester_id = p.id)
    )
  order by p.login_id
  limit 5;
$$;

create or replace function public.send_friend_request(target_login_id text)
returns void
language plpgsql
security definer set search_path = ''
as $$
declare target_id uuid;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select p.id into target_id from public.profiles p
  where p.login_id = lower(btrim(target_login_id));
  if target_id is null then raise exception 'user_not_found'; end if;
  if target_id = auth.uid() then raise exception 'cannot_add_self'; end if;

  insert into public.friendships(requester_id, addressee_id)
  values (auth.uid(), target_id);
exception when unique_violation then
  raise exception 'friendship_already_exists';
end;
$$;

create or replace function public.respond_friend_request(request_id bigint, accept_request boolean)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  if accept_request then
    update public.friendships
      set status = 'accepted', accepted_at = now()
      where id = request_id and addressee_id = auth.uid() and status = 'pending';
  else
    delete from public.friendships
      where id = request_id and addressee_id = auth.uid() and status = 'pending';
  end if;
  if not found then raise exception 'friend_request_not_found'; end if;
end;
$$;

create or replace function public.friend_dashboard()
returns table(
  friendship_id bigint,
  user_id uuid,
  login_id text,
  display_name text,
  relationship text,
  presence_status text
)
language sql
security definer set search_path = ''
as $$
  with related as (
    select f.id as friendship_id,
      case when f.requester_id = auth.uid() then f.addressee_id else f.requester_id end as friend_id,
      case
        when f.status = 'accepted' then 'accepted'
        when f.addressee_id = auth.uid() then 'incoming'
        else 'outgoing'
      end as relationship
    from public.friendships f
    where f.requester_id = auth.uid() or f.addressee_id = auth.uid()
  )
  select r.friendship_id, p.id, p.login_id::text, p.display_name, r.relationship,
    case
      when exists (
        select 1 from public.game_participants gp
        join public.game_rooms gr on gr.id = gp.room_id
        where gp.user_id = p.id and gr.status = 'active' and gr.expires_at > now()
      ) then 'playing'
      when up.last_seen_at >= now() - interval '1 minute' then 'online'
      else 'offline'
    end as presence_status
  from related r
  join public.profiles p on p.id = r.friend_id
  left join public.user_presence up on up.user_id = p.id
  order by case r.relationship when 'incoming' then 0 when 'accepted' then 1 else 2 end, p.display_name;
$$;

create or replace function public.touch_presence()
returns table(
  friendship_id bigint,
  user_id uuid,
  login_id text,
  display_name text,
  relationship text,
  presence_status text
)
language plpgsql
security definer set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  insert into public.user_presence(user_id, last_seen_at) values (auth.uid(), now())
    on conflict (user_id) do update set last_seen_at = excluded.last_seen_at;
  return query select * from public.friend_dashboard();
end;
$$;

create or replace function public.start_game_room(
  requested_game_id text,
  requested_game_mode text,
  participants jsonb
)
returns uuid
language plpgsql
security definer set search_path = ''
as $$
declare
  new_room_id uuid;
  participant jsonb;
  participant_user_id uuid;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if requested_game_id not in ('skullking', 'tichu', 'generic') then raise exception 'invalid_game'; end if;
  if jsonb_typeof(participants) <> 'array' or jsonb_array_length(participants) < 1 then
    raise exception 'participants_required';
  end if;

  insert into public.game_rooms(game_id, game_mode, host_user_id)
  values (requested_game_id, left(coalesce(requested_game_mode, ''), 30), auth.uid())
  returning id into new_room_id;

  for participant in select value from jsonb_array_elements(participants)
  loop
    participant_user_id := nullif(participant ->> 'user_id', '')::uuid;
    if participant_user_id is not null and participant_user_id <> auth.uid() and not exists (
      select 1 from public.friendships f
      where f.status = 'accepted'
        and ((f.requester_id = auth.uid() and f.addressee_id = participant_user_id)
          or (f.addressee_id = auth.uid() and f.requester_id = participant_user_id))
    ) then
      raise exception 'participant_is_not_friend';
    end if;
    insert into public.game_participants(room_id, user_id, display_name, team_name)
    values (
      new_room_id,
      participant_user_id,
      left(btrim(participant ->> 'display_name'), 50),
      nullif(left(btrim(participant ->> 'team_name'), 30), '')
    );
  end loop;
  return new_room_id;
end;
$$;

create or replace function public.finish_game_room(requested_room_id uuid, results jsonb)
returns void
language plpgsql
security definer set search_path = ''
as $$
declare result_item jsonb;
begin
  if not exists (
    select 1 from public.game_rooms gr
    where gr.id = requested_room_id and gr.host_user_id = auth.uid()
      and gr.status = 'active' and gr.expires_at > now()
  ) then raise exception 'active_room_not_found'; end if;

  for result_item in select value from jsonb_array_elements(results)
  loop
    update public.game_participants
      set final_score = (result_item ->> 'final_score')::integer,
          final_rank = (result_item ->> 'final_rank')::integer
      where room_id = requested_room_id
        and id = (result_item ->> 'participant_id')::bigint;
  end loop;

  if exists (
    select 1 from public.game_participants gp
    where gp.room_id = requested_room_id and (gp.final_score is null or gp.final_rank is null)
  ) then raise exception 'incomplete_results'; end if;

  update public.game_rooms set status = 'completed', ended_at = now()
  where id = requested_room_id;
end;
$$;

create or replace function public.cancel_game_room(requested_room_id uuid)
returns void
language sql
security definer set search_path = ''
as $$
  delete from public.game_rooms
  where id = requested_room_id and host_user_id = auth.uid() and status = 'active';
$$;

create or replace function public.my_game_history()
returns table(room_id uuid, game_id text, game_mode text, started_at timestamptz, ended_at timestamptz,
  display_name text, team_name text, final_score integer, final_rank integer)
language sql
security definer set search_path = ''
as $$
  select gr.id, gr.game_id, gr.game_mode, gr.started_at, gr.ended_at,
    gp.display_name, gp.team_name, gp.final_score, gp.final_rank
  from public.game_participants gp
  join public.game_rooms gr on gr.id = gp.room_id
  where gp.user_id = auth.uid() and gr.status = 'completed'
  order by gr.ended_at desc;
$$;

create or replace function public.win_rankings()
returns table(user_id uuid, login_id text, display_name text, wins bigint, games bigint)
language sql
security definer set search_path = ''
as $$
  select p.id, p.login_id::text, p.display_name,
    count(*) filter (where gp.final_rank = 1) as wins,
    count(*) as games
  from public.profiles p
  join public.game_participants gp on gp.user_id = p.id
  join public.game_rooms gr on gr.id = gp.room_id and gr.status = 'completed'
  group by p.id, p.login_id, p.display_name
  order by wins desc, games asc, p.display_name;
$$;

create or replace function public.cleanup_expired_game_rooms()
returns bigint
language plpgsql
security definer set search_path = ''
as $$
declare removed bigint;
begin
  delete from public.game_rooms where status = 'active' and expires_at <= now();
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.is_login_id_available(text) from public;
grant execute on function public.is_login_id_available(text) to anon, authenticated;
revoke all on function public.my_profile() from public;
grant execute on function public.my_profile() to authenticated;
revoke all on function public.search_profiles(text) from public;
grant execute on function public.search_profiles(text) to authenticated;
revoke all on function public.send_friend_request(text) from public;
grant execute on function public.send_friend_request(text) to authenticated;
revoke all on function public.respond_friend_request(bigint, boolean) from public;
grant execute on function public.respond_friend_request(bigint, boolean) to authenticated;
revoke all on function public.friend_dashboard() from public;
grant execute on function public.friend_dashboard() to authenticated;
revoke all on function public.touch_presence() from public;
grant execute on function public.touch_presence() to authenticated;
revoke all on function public.start_game_room(text, text, jsonb) from public;
grant execute on function public.start_game_room(text, text, jsonb) to authenticated;
revoke all on function public.finish_game_room(uuid, jsonb) from public;
grant execute on function public.finish_game_room(uuid, jsonb) to authenticated;
revoke all on function public.cancel_game_room(uuid) from public;
grant execute on function public.cancel_game_room(uuid) to authenticated;
revoke all on function public.my_game_history() from public;
grant execute on function public.my_game_history() to authenticated;
revoke all on function public.win_rankings() from public;
grant execute on function public.win_rankings() to authenticated;
revoke all on function public.cleanup_expired_game_rooms() from public;

-- Run cleanup every five minutes. Re-running this migration replaces the existing job.
create extension if not exists pg_cron with schema pg_catalog;
do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'cleanup-expired-board-game-rooms';
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
  perform cron.schedule(
    'cleanup-expired-board-game-rooms',
    '*/5 * * * *',
    'select public.cleanup_expired_game_rooms();'
  );
end $$;
