-- Board Game Score - public board-game guide schema
-- Login, friends, presence, rankings and remote game history are not used.

create table if not exists public.game_guides (
  id bigint generated by default as identity primary key,
  slug text not null,
  version_key text not null,
  title_ko text not null,
  title_en text not null,
  aliases text[] not null default '{}',
  edition_label text not null,
  release_year smallint,
  player_count text not null,
  play_time text not null,
  goal text not null,
  setup text[] not null default '{}',
  gameplay text[] not null default '{}',
  special_rules text[] not null default '{}',
  pirate_abilities text[] not null default '{}',
  scoring text[] not null default '{}',
  end_condition text not null,
  source_name text not null,
  source_url text not null,
  sort_order smallint not null default 0,
  published boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint game_guides_slug_version_unique unique (slug, version_key)
);

alter table public.game_guides enable row level security;

drop policy if exists "game_guides_public_read" on public.game_guides;
create policy "game_guides_public_read"
  on public.game_guides for select
  to anon, authenticated
  using (published = true);

grant select on public.game_guides to anon, authenticated;
